### ISSUE TITLE
Migration path with custom RBAC groups

### ISSUE THREAD

**Issue by thatarchguy** [aidanmelen/terraform-aws-eks-auth#22]
You suggest that users should migrate to version 18.20 of the official EKS module which supports handling the configmap directly in the cluster creation. 

However, I ran into a problem.
I use your other module, terraform-kubernetes-rbac, to set up all of the RBAC cluster roles and permissions, and then I use the terraform-aws-eks-auth module to map the AWS users to those roles. This is all after initial cluster creation.

The EKS module does not have the ability to create RBAC groups, so would I use the new aws_auth_roles feature to map to groups that do not exist? Then apply the RBAC module?

**Comment by aidanmelen** [comment]
Thanks for opening this issue @thatarchguy 

I understand that you need help migrating to the`terraform-aws-eks` module while continuing to setup RBAC roles and permissions using the `terraform-kubernetes-rbac` module. 

What does your terraform currently look like? I am guessing your terraform looks something like this:

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = "my-cluster"
  cluster_version = "1.22"
}

module "rbac" {
  source  = "aidanmelen/rbac/kubernetes"
  version = "0.1.1"

  cluster_roles = {
    # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example
    # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example
    "secret-reader-global" = {
      # "namespace" omitted since ClusterRoles are not namespaced
      cluster_role_rules = [
        {
          api_groups = [""]
          resources  = ["secrets"]
          verbs      = ["get", "watch", "list"]
        },
      ]

      # This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
      cluster_role_binding_name = "read-secrets-global"
      cluster_role_binding_subjects = [
        {
          kind     = "Group"
          name     = "manager" # Name is case sensitive
          apiGroup = "rbac.authorization.k8s.io"
        }
      ]
    }
  }
}

module "eks-auth" {
  source  = "terraform-aws-modules/eks-auth/aws"
  version = "18.26.6"

  eks = module.eks

  map_roles = [
    {
      rolearn  = "arn:aws:iam::66666666666:role/role1"
      username = "role1"
      groups   = ["manager"] # reference to manager group that will eventually exist on the cluster
    },
  ]
}
```

and you may want to try something like this:

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.0"

  cluster_name    = "my-cluster"
  cluster_version = "1.22"

  # aws-auth configmap
  manage_aws_auth_configmap = true

  map_roles = [
    {
      rolearn  = "arn:aws:iam::66666666666:role/role1"
      username = "role1"
      groups   = ["manager"]
    },
  ]
}

module "rbac" {
  source  = "aidanmelen/rbac/kubernetes"
  version = "0.1.1"

  cluster_roles = {
    # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example
    # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example
    "secret-reader-global" = {
      # "namespace" omitted since ClusterRoles are not namespaced
      cluster_role_rules = [
        {
          api_groups = [""]
          resources  = ["secrets"]
          verbs      = ["get", "watch", "list"]
        },
      ]

      # This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
      cluster_role_binding_name = "read-secrets-global"
      cluster_role_binding_subjects = [
        {
          kind     = "Group"
          name     = "manager" # Name is case sensitive
          apiGroup = "rbac.authorization.k8s.io"
        }
      ]
    }
  }
}
```

Both the `terraform-aws-eks-aws-auth` module and now the `terraform-aws-eks` modules work by managing the `aws-auth` ConfigMap on the cluster. We can add references to users, roles, and accounts that don't exist at cluster creation. We can create the EKS cluster, configure the `aws-auth` and then retroactively create the user, roles, accounts that it references. This should work because the dependencies exist inside the k8s cluster and not at the Terraform resource level.

For the sake of example, I simply hardcoded the `"master"` group name in both modules. If you are creating many groups, then it might be best to store the names in a `local` value and reference the group names in both the eks module and rbac modules.

**Comment by thatarchguy** [comment]
This is very similar to what we are dealing with. Thank you so much. 

We are using terragrunt and calling the EKS module directly from it. So this would end up being two different terragrunt applies - one to create the eks cluster and auth mapping, and one to create the RBAC. 

Originally we had two different grunt applies as well - one to create the eks cluster, and one to create the auth mapping and RBAC. 

A little nuanced, but it will be the same result.
